### ISSUE TITLE
Upgrades

### ISSUE THREAD

**Issue by wilsonsj100** [COMPASS-DOE/whattheflux#3]
Roberta and I were chatting yesterday and she said she had found an issue / had some comments with our code. 
- she said she was having trouble when there were TWO Licors collecting data over the SAME time frame, typically in CB we only have one person doing fluxes at a time so we don't have overlapping date ranges and time stamps from two different serial numbers, but this seems like something we could fix by sorting the data by Licor serial number then pulling times out 
- she mentioned she may have other comments she might have emailed to you last year? (I asked her to email them to me as well)

**Comment by bpbond** [comment]
>comments she might have emailed to you last year

Hmm, I see technical support questions about `ghg-processor` but not anything more than that. Hopefully she can re-send!

**Comment by bpbond** [comment]
Closing as I think we're good with all of these.
