### ISSUE TITLE
ppb to nmol 

### ISSUE THREAD

**Issue by wilsonsj100** [COMPASS-DOE/whattheflux#42]
Hey Ben, 
After talking with Genevieve about the units thing. I am thinking it might be most helpful if we duplicate the wtf_ppm_to_umol() function and call it wtf_ppb_to_nmol(). This seems a bit redundant, but I think it will make it easiest for the users because then they can choose which function to use based on what units the instrument gives us. In someways it is annoying that the licor uses ppb for CH4 and N2O, but ppm for CO2; however, it is what they do. 

Let me know what you think about this. If you are on board then I will add in this other function and some text to the manuscript regarding this change.

**Comment by bpbond** [comment]
This is fine; it'll be using the exact same code under the hood, but clearer for users, agreed..
