### ISSUE TITLE
LI-7820

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/whattheflux#6]
@wilsonsj100 Do you have a couple sample LI-7820 files you could send me?

**Comment by wilsonsj100** [comment]
I have asked for one from Genevieve or Alia - will report back asap

**Comment by wilsonsj100** [comment]
Here is an example file (see attached) - thanks Genevieve! 
[TG20-01182-2023-11-08T100000.zip](https://github.com/COMPASS-DOE/whattheflux/files/14166452/TG20-01182-2023-11-08T100000.zip)

let me know if this doesn't work - its a big file

**Comment by bpbond** [comment]
Thank you!

**Comment by bpbond** [comment]
One question: this file has a "txt" extension. Do you or Genevieve rename it to have that? I'm asking because the 7810 files have a "data" extension. Thanks!

**Comment by wilsonsj100** [comment]
[TG20-01182-2023-11-08T100000.zip](https://github.com/COMPASS-DOE/whattheflux/files/14171566/TG20-01182-2023-11-08T100000.zip)

Here it is with .data that comes off the instrument. Sorry I changed it out of habit - oops

**Comment by bpbond** [comment]
Totally fine, no need to send second file! Just wanted to confirm--thanks.
